[package]
name = "kata"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.12.3", features = ["default"] }
serde = { version = "1.0.217", features = ["derive"] }
bson = "2.13.0"
bytes = "1.10.0"
tonic-build = "0.12.3"
tokio = { version = "1.43.0", features = ["full"] }
